### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by didierganthier** [FredsephT32/Set-Up-Mobile-Portfolio#14]
The project is great, you're working hard

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Great job done
- Descriptive PR and README file
- Great representation of the design

But there's only one thing I would mention in order to improve it:

## Suggested Changes 💻
- [x] The data isn't being loaded back to the input fields when the browser is refreshed as required for this project. In order to do that you could check if the `object` exists (the one you stored and set the input values to the corresponding values.

Happy Coding! 😎✨

**Comment by FredsephT32** [comment]
I know what was the problem😅, I for my live version of my webpage I was Using a different branch instead of the master branch and the live GitHub deployed webpage was like 25 commits behind the master, thanks for letting me know that!🙈
